import { I18n } from '@affine/i18n';

const labels: Record<string, string> = {
  others: 'com.affine.ai.action-label.others',
  'edit text': 'com.affine.ai.action-label.edit-text',
  'Translate to': 'com.affine.ai.action-label.translate-to',
  'Change tone to': 'com.affine.ai.action-label.change-tone-to',
  'Improve writing': 'com.affine.ai.action-label.improve-writing',
  'Make it longer': 'com.affine.ai.action-label.make-it-longer',
  'Make it shorter': 'com.affine.ai.action-label.make-it-shorter',
  'Continue writing': 'com.affine.ai.action-label.continue-writing',
  'draft from text': 'com.affine.ai.action-label.draft-from-text',
  'Write an article about this':
    'com.affine.ai.action-label.write-an-article-about-this',
  'Write a tweet about this':
    'com.affine.ai.action-label.write-a-tweet-about-this',
  'Write a poem about this':
    'com.affine.ai.action-label.write-a-poem-about-this',
  'Write a blog post about this':
    'com.affine.ai.action-label.write-a-blog-post-about-this',
  'Brainstorm ideas about this':
    'com.affine.ai.action-label.brainstorm-ideas-about-this',
  'review image': 'com.affine.ai.action-label.review-image',
  'Explain this image': 'com.affine.ai.action-label.explain-this-image',
  'review code': 'com.affine.ai.action-label.review-code',
  'Explain this code': 'com.affine.ai.action-label.explain-this-code',
  'Check code error': 'com.affine.ai.action-label.check-code-error',
  'review text': 'com.affine.ai.action-label.review-text',
  'Fix spelling': 'com.affine.ai.action-label.fix-spelling',
  'Fix grammar': 'com.affine.ai.action-label.fix-grammar',
  'Explain selection': 'com.affine.ai.action-label.explain-selection',
  'generate from text': 'com.affine.ai.action-label.generate-from-text',
  Summarize: 'com.affine.ai.action-label.summarize',
  'Generate headings': 'com.affine.ai.action-label.generate-headings',
  'Generate outline': 'com.affine.ai.action-label.generate-outline',
  'Generate an image': 'com.affine.ai.action-label.generate-an-image',
  'Expand from this mind map node':
    'com.affine.ai.action-label.expand-from-this-mind-map-node',
  'Brainstorm ideas with mind map':
    'com.affine.ai.action-label.brainstorm-ideas-with-mind-map',
  'Regenerate mind map': 'com.affine.ai.action-label.regenerate-mind-map',
  'Generate presentation': 'com.affine.ai.action-label.generate-presentation',
  'Make it real': 'com.affine.ai.action-label.make-it-real',
  'AI image filter': 'com.affine.ai.action-label.ai-image-filter',
  'Image processing': 'com.affine.ai.action-label.image-processing',
  'Generate a caption': 'com.affine.ai.action-label.generate-a-caption',
  'Find actions': 'com.affine.ai.action-label.find-actions',
  'Continue in AI Chat': 'com.affine.ai.action-label.continue-in-ai-chat',
  English: 'com.affine.ai.action-label.english',
  'Brazilian Portuguese': 'com.affine.ai.action-label.brazilian-portuguese',
  Spanish: 'com.affine.ai.action-label.spanish',
  German: 'com.affine.ai.action-label.german',
  French: 'com.affine.ai.action-label.french',
  Italian: 'com.affine.ai.action-label.italian',
  'Simplified Chinese': 'com.affine.ai.action-label.simplified-chinese',
  'Traditional Chinese': 'com.affine.ai.action-label.traditional-chinese',
  Japanese: 'com.affine.ai.action-label.japanese',
  Russian: 'com.affine.ai.action-label.russian',
  Korean: 'com.affine.ai.action-label.korean',
  Professional: 'com.affine.ai.action-label.professional',
  Informal: 'com.affine.ai.action-label.informal',
  Friendly: 'com.affine.ai.action-label.friendly',
  Critical: 'com.affine.ai.action-label.critical',
  Humorous: 'com.affine.ai.action-label.humorous',
  'Clay style': 'com.affine.ai.action-label.clay-style',
  'Sketch style': 'com.affine.ai.action-label.sketch-style',
  'Anime style': 'com.affine.ai.action-label.anime-style',
  'Pixel style': 'com.affine.ai.action-label.pixel-style',
  Clearer: 'com.affine.ai.action-label.clearer',
  'Remove background': 'com.affine.ai.action-label.remove-background',
  'Convert to sticker': 'com.affine.ai.action-label.convert-to-sticker',
  'Select template': 'com.affine.ai.action-label.select-template',
  'Show detail': 'com.affine.ai.action-label.show-detail',
  'Ask AI': 'com.affine.ai.action-label.ask-ai',
  Copy: 'com.affine.ai.action-label.copy',
  'AI outputs can be misleading or wrong':
    'com.affine.ai.action-label.ai-outputs-can-be-misleading-or-wrong',
  Answer: 'com.affine.ai.action-label.answer',
  'Send to AI': 'com.affine.ai.action-label.send-to-ai',
  Upgrade: 'com.affine.ai.action-label.upgrade',
  'Drop to attach': 'com.affine.ai.action-label.drop-to-attach',
  'Add chat': 'com.affine.ai.action-label.add-chat',
  'Open this doc': 'com.affine.ai.action-label.open-this-doc',
  'Empty history': 'com.affine.ai.action-label.empty-history',
  'New Chat': 'com.affine.ai.action-label.new-chat',
  'Chat History': 'com.affine.ai.action-label.chat-history',
  'No Result': 'com.affine.ai.action-label.no-result',
  'Edited Content': 'com.affine.ai.action-label.edited-content',
  'Insert below': 'com.affine.ai.action-label.insert-below',
  'Create new doc': 'com.affine.ai.action-label.create-new-doc',
  Deleted: 'com.affine.ai.action-label.deleted',
  Inserted: 'com.affine.ai.action-label.inserted',
  'with your docs': 'com.affine.ai.action-label.with-your-docs',
  'AI chat block': 'com.affine.ai.action-label.ai-chat-block',
};

export function aiActionLabel(name: string) {
  return labels[name] ? I18n.t(labels[name]) : name;
}
